### ISSUE TITLE
Feature Request: Provide a way to deserialize polymorphic lists

### ISSUE THREAD

**Issue by mvollmary** [arangodb/java-velocypack#1]
The deserialization should provide a way to deserialize polymorphic lists.
Presumably for this we have to store information about the concrete implementation in vpack (like jackson with `JsonTypeInfo`).

**Comment by rocketraman** [comment]
See issue #9

**Comment by mvollmary** [comment]
Added support for generic types/polymorphic lists in release 1.4.0. (Java driver includes this in release 5.0.0)
