### ISSUE TITLE
Support for heterogeneous arrays

### ISSUE THREAD

**Issue by wajda** [arangodb/java-velocypack#12]
When serializing an array of an abstract class or interface, a type hint should be added to the items, just like it's done for generic lists.

**Comment by wajda** [comment]
@mpv1989
I've created a pull request that fixes this issue. Can you please take a look?

Also I would like to add support for generic arrays and improve API for custom serializers. I'll create separate issues for that.

**Comment by rashtao** [comment]
@wajda is this issue fixed by https://github.com/arangodb/java-velocypack/pull/13?

**Comment by wajda** [comment]
@rashtao Yes, please close it.
