### ISSUE TITLE
VPackBuilder misses add(Byte)

### ISSUE THREAD

**Issue by CuriusAlgo** [arangodb/java-velocypack#21]
It has `add(final String attribute, final Byte value)`, so I would have expected a `add(final Byte value)` to be present, like there are for all other data types. `addTagged(final long tag, final Byte value)` is also missing.

**Comment by rashtao** [comment]
I created this PR https://github.com/arangodb/java-velocypack/pull/24 that should solve the problem.
Feel free to review or add comments to it.
