### ISSUE TITLE
VPackParser::fromJson has no variant that takes VPackBuilder.BuilderOptions

### ISSUE THREAD

**Issue by CuriusAlgo** [arangodb/java-velocypack#22]
The VPackBuilder used while parsing the Json string is always created with the default options, so it is impossible to get a VPackSlice with unindexed arrays/objects.

**Comment by rashtao** [comment]
I created this PR https://github.com/arangodb/java-velocypack/pull/23 that should solve the problem.
Feel free to review or add comments to it.
