### ISSUE TITLE
VPackParser.toJson v2.5.3 parses String with new lines different than v2.5.2

### ISSUE THREAD

**Issue by joscht-73** [arangodb/java-velocypack#29]
Arangodb content like _{\\n  \\"description\\": \\"String with new line\\"\\n}_ was ok for version 2.5.2.
Version 2.5.3 requires _{\\\\n  \\"description\\": \\"String with new line\\"\\\\n}_ otherwise Jackson ObjectMapper throws Exception with json String from VPackParser.toJson.
Is this change intentional or a bug?
See [example v2.5.3](https://github.com/joscht-73/java-velocypack/blob/new-line-v2.5.3/src/test/java/parse/newline/VPackNewLineTest.java)  vs [example v2.5.2](https://github.com/joscht-73/java-velocypack/blob/new-line-v2.5.2/src/test/java/parse/newline/VPackNewLineTest.java)

**Comment by rashtao** [comment]
Thanks for reporting, it should be fixed by https://github.com/arangodb/java-velocypack/commit/f658bcc6a9a12d511717e3974c3707826db3c380
I will add tests to avoid future regressions.
