### ISSUE TITLE
How to migrate from @SerializedName an @Expose

### ISSUE THREAD

**Issue by idoub** [arangodb/java-velocypack#32]
With the latest update, the annotations @SerializezdName and @Expose have been removed from this library and as far as I can tell, the functionality those provided no longer exists. Is there a migration process to move code that used those annotations to the latest version?

**Comment by rashtao** [comment]
In version `3.0.0` all data binding capabilities have been removed in favor of [jackson-dataformat-velocypack](https://github.com/arangodb/jackson-dataformat-velocypack).

The functionalities of `@SerializezdName` and `@Expose` can be now implemented using  [`@JsonProperty`](https://fasterxml.github.io/jackson-annotations/javadoc/2.14/com/fasterxml/jackson/annotation/JsonProperty.html), [`@JsonInclude`](https://fasterxml.github.io/jackson-annotations/javadoc/2.14/com/fasterxml/jackson/annotation/JsonInclude.html) and [`@JsonIgnore`](https://fasterxml.github.io/jackson-annotations/javadoc/2.14/com/fasterxml/jackson/annotation/JsonIgnore.html).

**Comment by idoub** [comment]
Thanks
